jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pipenv run python preprocessor/null_value_cleaner.py test
      - store_test_results:
          path: test-results
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build