jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: run tests
          command: |
                . venv/bin/activate
                 python manage.py test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test