jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv

  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pipenv install -r requirements.txt
            pipenv install pytest
            pipenv run pytest

  static_analysis_preprocessor:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pipenv install -r requirements.txt
            pipenv install pylint
            pipenv run pylint preprocessor

  static_analysis_integration_tests:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pipenv install -r requirements.txt
            pipenv install pylint
            pipenv run pylint tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - static_analysis_preprocessor:
          requires:
            - test
      - static_analysis_integration_tests:
          requires:
            - test

